# imported from: agentwall via nixis policy import
apiVersion: nixis.io/v1
kind: PolicyTemplate
metadata:
    name: agentwall-query-database-options-required-limit
    annotations:
        nixis.io/imported-from: nixis-import-1966544447.yaml
        nixis.io/severity: low
spec:
    description: 'AgentWall required field: query_database.options.limit'
    matchConstraints:
        tools:
            - query_database
    validations:
        - expression: tool == "query_database" && request.args.limit == ""
          message: Required field limit is missing
          action: DENY
    defaultAction: ALLOW
