# IMPORTED FROM: open-policy-agent/gatekeeper-library
CONSTRAINT: K8sPSPPrivilegedContainer
# imported from: gatekeeper-library via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: gatekeeper-psp-privileged-container
    annotations:
        aegis.io/imported-from: aegis-import-2057840007.yaml
        aegis.io/original-kind: K8sPSPPrivilegedContainer
        aegis.io/severity: high
        aegis.io/source: open-policy-agent/gatekeeper-library
spec:
    description: 'OPA Gatekeeper constraint psp-privileged-container (kind: K8sPSPPrivilegedContainer)'
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.matches("kubectl.*privileged.*true")
          message: 'OPA Gatekeeper constraint psp-privileged-container (kind: K8sPSPPrivilegedContainer)'
          action: DENY
    defaultAction: ALLOW
