# IMPORTED FROM: open-policy-agent/gatekeeper-library
CONSTRAINT: K8sPSPForbiddenSysctls
# imported from: gatekeeper-library via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: gatekeeper-psp-forbidden-sysctls
    annotations:
        aegis.io/imported-from: aegis-import-1839296989.yaml
        aegis.io/original-kind: K8sPSPForbiddenSysctls
        aegis.io/severity: high
        aegis.io/source: open-policy-agent/gatekeeper-library
spec:
    description: 'OPA Gatekeeper constraint psp-forbidden-sysctls (kind: K8sPSPForbiddenSysctls)'
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.matches("kubectl.*sysctl.*")
          message: 'OPA Gatekeeper constraint psp-forbidden-sysctls (kind: K8sPSPForbiddenSysctls)'
          action: DENY
    defaultAction: ALLOW
