# imported from: rules via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: falco-delete-or-rename-shell-history
    annotations:
        aegis.io/falco-tags: maturity_incubating,host,container,process,filesystem,mitre_defense_evasion,T1070
        aegis.io/imported-from: aegis-import-2621062960.yaml
        aegis.io/severity: medium
        aegis.io/source-rule: Delete or rename shell history
spec:
    description: |
        Detect shell history deletion, frequently used by unsophisticated adversaries to eliminate evidence. Note that it can also trigger when exiting a Terminal shell, such as with `kubectl exec`, which may introduce some noise.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: 'tool == "Bash" && (request.args.command.matches(".*rm\\s+.*\\.(bash_history|zsh_history|sh_history).*") || request.args.command.matches(".*history\\s+-[cw].*") || request.args.command.contains("HISTFILE=/dev/null") || request.args.command.matches(".*ln\\s+.*\\.bash_history.*"))'
          message: 'Falco rule violated: Delete or rename shell history'
          action: REQUIRE_APPROVAL
    defaultAction: ALLOW
