# imported from: rules via nixis policy import
apiVersion: nixis.io/v1
kind: PolicyTemplate
metadata:
    name: falco-launch-privileged-container
    annotations:
        nixis.io/falco-tags: maturity_incubating,container,cis,mitre_execution,T1610,PCI_DSS_10.2.5
        nixis.io/imported-from: nixis-import-2621062960.yaml
        nixis.io/severity: low
        nixis.io/llm-confidence: medium
        nixis.io/source-rule: Launch Privileged Container
spec:
    description: |
        Detect the initial process initiation within a privileged container, with exemptions for known and trusted images. This rule primarily serves as an excellent auditing mechanism since highly privileged containers, when compromised, can result in significant harm. For instance, if another rule triggers within such a privileged container, it could be seen as more suspicious, prompting a closer inspection.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: 'tool == "Bash" && request.args.command.matches(".*(docker\\s+run|kubectl\\s+run).*--privileged.*")'
          message: 'Falco rule violated: Launch Privileged Container'
          action: AUDIT
    defaultAction: ALLOW
