# IMPORT_TODO: Falco condition uses kernel or macro fields that cannot be automatically translated — manual review required. Original condition: spawned_process and container and network_tool_procs and not user_known_network_tool_activities
# imported from: rules via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: falco-launch-suspicious-network-tool-in-container
    annotations:
        aegis.io/falco-tags: maturity_incubating,container,network,process,mitre_execution,T1059
        aegis.io/imported-from: aegis-import-3831796007.yaml
        aegis.io/severity: low
        aegis.io/source-rule: Launch Suspicious Network Tool in Container
spec:
    description: |
        Detect network tools (like netcat, nmap, tcpdump, socat, and more) launched within containers without any additional filters. This serves as a valuable general detection, but it's recommended to invest engineering effort to fine-tune it and prevent a high volume of legitimate logs. This rule complements the more specific "Netcat Remote Code Execution in Container" rule.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: "false"
          message: 'Falco rule violated: Launch Suspicious Network Tool in Container'
          action: REQUIRE_APPROVAL
    defaultAction: ALLOW
