# imported from: rules via nixis policy import
apiVersion: nixis.io/v1
kind: PolicyTemplate
metadata:
    name: falco-system-user-interactive
    annotations:
        nixis.io/falco-tags: maturity_stable,host,container,users,mitre_execution,T1059,NIST_800-53_AC-2
        nixis.io/imported-from: nixis-import-999705196.yaml
        nixis.io/severity: low
        nixis.io/llm-confidence: medium
        nixis.io/source-rule: System user interactive
spec:
    description: |
        System (e.g. non-login) users spawning new processes. Can add custom service users (e.g. apache or mysqld). 'Interactive' is defined as new processes as descendants of an ssh session or login process. Consider further tuning by only looking at processes in a terminal / tty (proc.tty != 0). A newer field proc.is_vpgid_leader could be of help to distinguish if the process was "directly" executed, for instance, in a tty, or executed as a descendant process in the same process group, which, for example, is the case when subprocesses are spawned from a script. Consider this rule as a great template rule to monitor interactive accesses to your systems more broadly. However, such a custom rule would be unique to your environment. The rule "Terminal shell in container" that fires when using "kubectl exec" is more Kubernetes relevant, whereas this one could be more interesting for the underlying host.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: 'tool == "Bash" && request.args.command.matches(".*\\bsu\\b\\s+(root|daemon|nobody|www-data|sys|bin|mail|games|man|lp|news|uucp).*")'
          message: 'Falco rule violated: System user interactive'
          action: AUDIT
    defaultAction: ALLOW
