# IMPORT_TODO: Falco condition uses kernel or macro fields that cannot be automatically translated — manual review required. Original condition: inbound_outbound and container and k8s.ns.name in (namespace_scope_network_only_subnet) and not network_local_subnet
# imported from: main via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: falco-network-connection-outside-local-subnet
    annotations:
        aegis.io/falco-tags: maturity_incubating,container,network,mitre_discovery,T1046,PCI_DSS_6.4.2
        aegis.io/imported-from: aegis-import-487448035.yaml
        aegis.io/severity: medium
        aegis.io/source-rule: Network Connection outside Local Subnet
spec:
    description: |
        Detect network traffic (inbound or outbound) from a container to a destination outside the local subnet. To operationalize this rule, profile your environment and update the template macro namespace_scope_network_only_subnet. Customizing network-related rules usually demands substantial engineering effort to ensure their functionality.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: "false"
          message: 'Falco rule violated: Network Connection outside Local Subnet'
          action: REQUIRE_APPROVAL
    defaultAction: ALLOW
