# imported from: rules via nixis policy import
apiVersion: nixis.io/v1
kind: PolicyTemplate
metadata:
    name: falco-detect-release-agent-file-container-escapes
    annotations:
        nixis.io/falco-tags: maturity_stable,container,process,mitre_privilege_escalation,T1611
        nixis.io/imported-from: nixis-import-999705196.yaml
        nixis.io/severity: critical
        nixis.io/llm-confidence: medium
        nixis.io/source-rule: Detect release_agent File Container Escapes
spec:
    description: |
        Detect an attempt to exploit a container escape using release_agent file. By running a container with certains capabilities, a privileged user can modify release_agent file and escape from the container.
    matchConstraints:
        tools:
            - Write
            - Edit
            - Bash
    validations:
        - expression: '(tool == "Write" || tool == "Edit") && request.args.path.endsWith("release_agent") || tool == "Bash" && request.args.command.contains("release_agent")'
          message: 'Falco rule violated: Detect release_agent File Container Escapes'
          action: DENY
    defaultAction: ALLOW
