# imported from: rules via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: falco-wrong-mitre-rule-multiple-techniques-and-missing-one-tactic
    annotations:
        aegis.io/falco-tags: host,container,filesystem,mitre_credential_access,mitre_discovery,T1555,T1212,T1020,T1552,T1083
        aegis.io/imported-from: aegis-import-1844418014.yaml
        aegis.io/severity: medium
        aegis.io/source-rule: wrong mitre rule multiple techniques and missing one tactic
spec:
    description: |
        Read sensitive file untrusted - an attempt to read any sensitive file (e.g. files containing user/password/authentication information). Exceptions are made for known trusted programs.
    matchConstraints:
        tools:
            - Read
            - Write
            - Edit
    validations:
        - expression: tool == "Bash" && request.args.command.matches("(?i)\\b(user_mgmt_binaries|userexec_binaries|package_mgmt_binaries|cron_binaries|read_sensitive_file_binaries|shell_binaries|hids_binaries|vpn_binaries|mail_config_binaries|nomachine_binaries|sshkit_script_binaries|in.proftpd|mandb|salt-call|salt-minion|postgres_mgmt_binaries|google_oslogin_)\\b")
          message: 'Falco rule violated: wrong mitre rule multiple techniques and missing one tactic'
          action: REQUIRE_APPROVAL
    defaultAction: ALLOW
