# imported from: rules via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: falco-exfiltrating-artifacts-via-kubernetes-control-plane
    annotations:
        aegis.io/falco-tags: maturity_incubating,container,filesystem,mitre_exfiltration,TA0010
        aegis.io/imported-from: aegis-import-2621062960.yaml
        aegis.io/severity: low
        aegis.io/llm-confidence: medium
        aegis.io/source-rule: Exfiltrating Artifacts via Kubernetes Control Plane
spec:
    description: |
        Detect the copying of artifacts from a container's file system using the Kubernetes control plane (kubectl cp). This rule can identify potential exfiltration of application secrets from containers' file systems, potentially revealing the outcomes of unauthorized access and control plane misuse via stolen identities (such as stolen credentials like Kubernetes serviceaccount tokens). Can be customized by the adopter to only monitor specific artifact paths, containers, or namespaces as needed.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: 'tool == "Bash" && (request.args.command.matches(".*kubectl\\s+cp\\s+.*") || (request.args.command.matches(".*kubectl.*exec.*") && request.args.command.contains("tar")))'
          message: 'Falco rule violated: Exfiltrating Artifacts via Kubernetes Control Plane'
          action: REQUIRE_APPROVAL
    defaultAction: ALLOW
