# imported from: rules via nixis policy import
apiVersion: nixis.io/v1
kind: PolicyTemplate
metadata:
    name: falco-mount-launched-in-privileged-container
    annotations:
        nixis.io/falco-tags: maturity_incubating,container,cis,filesystem,mitre_privilege_escalation,T1611
        nixis.io/imported-from: nixis-import-2621062960.yaml
        nixis.io/severity: medium
        nixis.io/llm-confidence: medium
        nixis.io/source-rule: Mount Launched in Privileged Container
spec:
    description: |
        Detect filesystem mounts (using the mount binary) within a privileged container. Due to the elevated privileges, this action could be one of the TTPs used in an attempt to escape from a container to the host. This type of action is often preceded by reconnaissance activities, for which you can also create custom rules.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: 'tool == "Bash" && request.args.command.matches(".*\\bmount\\s+(/|--bind|--rbind|-o|-t).*") && !request.args.command.contains("--help")'
          message: 'Falco rule violated: Mount Launched in Privileged Container'
          action: REQUIRE_APPROVAL
    defaultAction: ALLOW
