# imported from: rules via nixis policy import
apiVersion: nixis.io/v1
kind: PolicyTemplate
metadata:
    name: falco-detect-crypto-miners-using-the-stratum-protocol
    annotations:
        nixis.io/falco-tags: maturity_sandbox,host,container,process,mitre_impact,T1496
        nixis.io/imported-from: nixis-import-1470842712.yaml
        nixis.io/severity: critical
        nixis.io/source-rule: Detect crypto miners using the Stratum protocol
spec:
    description: |
        Miners commonly specify the mining pool to connect to using a URI that starts with "stratum+tcp". However, this rule is highly specific to this technique, and matching command-line arguments can generally be bypassed quite easily.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.contains("stratum+tcp")
          message: 'Falco rule violated: Detect crypto miners using the Stratum protocol'
          action: DENY
    defaultAction: ALLOW
