# imported from: rules via nixis policy import
apiVersion: nixis.io/v1
kind: PolicyTemplate
metadata:
    name: falco-unprivileged-delegation-of-page-faults-handling-to-a-userspace-process
    annotations:
        nixis.io/falco-tags: maturity_sandbox,host,container,process,mitre_defense_evasion,TA0005
        nixis.io/imported-from: nixis-import-1470842712.yaml
        nixis.io/severity: critical
        nixis.io/source-rule: Unprivileged Delegation of Page Faults Handling to a Userspace Process
spec:
    description: |
        Detect a successful unprivileged userfaultfd syscall, which could serve as an attack primitive for exploiting other vulnerabilities. To fine-tune this rule, consider using the template list "user_known_userfaultfd_processes".
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: 'tool == "Bash" && request.args.command.contains("userfaultfd")'
          message: 'Falco rule violated: Unprivileged Delegation of Page Faults Handling to a Userspace Process'
          action: DENY
    defaultAction: ALLOW
