# imported from: policies via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-require-imagepullsecrets-check-for-image-pull-secrets-pod
    annotations:
        aegis.io/imported-from: aegis-import-3720630644.yaml
        aegis.io/severity: low
        kyverno.io/category: Sample
spec:
    description: Some registries, both public and private, require credentials in order to pull images from them. This policy checks those images and if they come from a registry other than ghcr.io or quay.io an `imagePullSecret` is required.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.matches("(?i)kubectl.*(delete\\s+pod|exec|run)")
          message: An `imagePullSecret` is required when pulling from this registry.
          action: AUDIT
    defaultAction: ALLOW
