# imported from: policies via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-disallow-ingress-nginx-custom-snippets-check-config-map-configmap
    annotations:
        aegis.io/imported-from: aegis-import-2241245480.yaml
        aegis.io/severity: low
        kyverno.io/category: Security, NGINX Ingress
spec:
    description: 'Users that can create or update ingress objects can use the custom snippets  feature to obtain all secrets in the cluster (CVE-2021-25742). This policy  disables allow-snippet-annotations in the ingress-nginx configuration and  blocks *-snippet annotations on an Ingress. See: https://github.com/kubernetes/ingress-nginx/issues/7837'
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.matches("(?i)kubectl.*(delete\s+configmap|create\s+configmap)")
          message: ingress-nginx allow-snippet-annotations must be set to false
          action: DENY
    defaultAction: ALLOW
