# imported from: policies via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-k6t-enforce-instancetype-k6t-ensure-instance-type-and-preference-virtualmachine
    annotations:
        aegis.io/imported-from: aegis-import-235143124.yaml
        aegis.io/severity: low
        kyverno.io/category: KubeVirt
spec:
    description: Check VirtualMachines and validate that they are using an instance type and preference.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.matches("(?i)kubectl.*")
          message: VirtualMachines must use instance types and preferences
          action: DENY
    defaultAction: ALLOW
