# imported from: policies via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-require-linkerd-mesh-injection-require-mesh-annotation-namespace
    annotations:
        aegis.io/imported-from: aegis-import-1475573898.yaml
        aegis.io/severity: medium
        kyverno.io/category: Linkerd
spec:
    description: Sidecar proxy injection in Linkerd may be handled at the Namespace level by setting the annotation `linkerd.io/inject` to `enabled`. This policy enforces that all Namespaces contain the annotation `linkerd.io/inject` set to `enabled`.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.matches("(?i)kubectl.*(delete\s+namespace|create\s+namespace)")
          message: All Namespaces must set the annotation `linkerd.io/inject` to `enabled`.
          action: REQUIRE_APPROVAL
    defaultAction: ALLOW
