# imported from: policies via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-require-ingress-https-has-tls-ingress
    annotations:
        aegis.io/imported-from: aegis-import-4272845450.yaml
        aegis.io/severity: medium
        kyverno.io/category: Other
spec:
    description: Ingress resources should only allow secure traffic by disabling HTTP and therefore only allowing HTTPS. This policy requires that all Ingress resources set the annotation `kubernetes.io/ingress.allow-http` to `"false"` and specify TLS in the spec.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.matches("(?i)kubectl.*")
          message: TLS must be defined.
          action: REQUIRE_APPROVAL
    defaultAction: ALLOW
