# imported from: policies via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-require-annotations-check-for-annotation-pod
    annotations:
        aegis.io/imported-from: aegis-import-1284308073.yaml
        aegis.io/severity: medium
        kyverno.io/category: Other
spec:
    description: 'Define and use annotations that identify semantic attributes of your application or Deployment. A common set of annotations allows tools to work collaboratively, describing objects in a common manner that all tools can understand. The recommended annotations describe applications in a way that can be queried. This policy validates that the annotation `corp.org/department` is specified with some value.      '
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.matches("(?i)kubectl.*(delete\s+pod|exec|run)")
          message: The annotation `corp.org/department` is required.
          action: REQUIRE_APPROVAL
    defaultAction: ALLOW
