# imported from: policies via nixis policy import
apiVersion: nixis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-disallow-selinux-selinux-user-role-pod
    annotations:
        nixis.io/imported-from: nixis-import-3152312964.yaml
        nixis.io/severity: medium
        kyverno.io/category: Pod Security Standards (Baseline)
spec:
    description: SELinux options can be used to escalate privileges and should not be allowed. This policy ensures that the `seLinuxOptions` field is undefined.
    matchConstraints:
        tools:
            - Write
            - Edit
    validations:
        - expression: '(tool == "Write" || tool == "Edit") && request.args.path.matches(".*\\.(yaml|yml|json)$") && request.args.content.matches("[\\s\\S]*seLinuxOptions:[\\s\\S]*(user:|role:)[\\s\\S]*")'
          message: Setting the SELinux user or role is forbidden. The fields spec.securityContext.seLinuxOptions.user, spec.securityContext.seLinuxOptions.role, spec.containers[*].securityContext.seLinuxOptions.user, spec.containers[*].securityContext.seLinuxOptions.role, spec.initContainers[*].securityContext.seLinuxOptions.user, spec.initContainers[*].securityContext.seLinuxOptions.role, spec.ephemeralContainers[*].securityContext.seLinuxOptions.user, and spec.ephemeralContainers[*].securityContext.seLinuxOptions.role must be unset.
          action: REQUIRE_APPROVAL
    defaultAction: ALLOW
