# imported from: policies via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-restrict-scale-scale-max-eight-deployment-scale
    annotations:
        aegis.io/imported-from: aegis-import-2893220568.yaml
        aegis.io/severity: medium
        kyverno.io/category: Other
spec:
    description: Pod controllers such as Deployments which implement replicas and permit the scale action use a `/scale` subresource to control this behavior. In addition to checks for creations of such controllers that their replica is in a certain shape, the scale operation and subresource needs to be accounted for as well. This policy, operable beginning in Kyverno 1.9, is a collection of rules which can be used to limit the replica count both upon creation of a Deployment and when a scale operation is performed.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.matches("(?i)kubectl.*")
          message: The replica count for this Deployment may not exceed 8.
          action: REQUIRE_APPROVAL
    defaultAction: ALLOW
