# imported from: policies via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-restrict-virtual-service-wildcard-block-virtual-service-wildcard-virtualservice
    annotations:
        aegis.io/imported-from: aegis-import-1648356309.yaml
        aegis.io/severity: medium
        kyverno.io/category: Istio
spec:
    description: Virtual Services optionally accept a wildcard as an alternative to precise matching. In some cases, this may be too permissive as it would direct unintended traffic to the given resource. This policy enforces that any Virtual Service host does not contain a wildcard character and allows for more governance when a single mesh deployment  model is used.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.matches("(?i)kubectl.*")
          message: Wildcards are not permitted as hosts.
          action: REQUIRE_APPROVAL
    defaultAction: ALLOW
