# imported from: policies via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-readwriteonce-pod-readwrite-pvc-single-pod-persistentvolumeclaim
    annotations:
        aegis.io/imported-from: aegis-import-2390191895.yaml
        aegis.io/severity: low
        kyverno.io/category: Sample
spec:
    description: Some stateful workloads with multiple replicas only allow a single Pod to write to a given volume at a time. Beginning in Kubernetes 1.22 and enabled by default in 1.27, a new setting called ReadWriteOncePod, available for CSI volumes only, allows volumes to be writable from only a single Pod. For more information see the blog https://kubernetes.io/blog/2023/04/20/read-write-once-pod-access-mode-beta/. This policy enforces that the accessModes for a PersistentVolumeClaim be set to ReadWriteOncePod.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.matches("(?i)kubectl.*")
          message: The accessMode must be set to ReadWriteOncePod.
          action: AUDIT
    defaultAction: ALLOW
