# imported from: policies via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-k10-validate-ns-by-preset-label-k10-validate-ns-by-preset-label-namespace
    annotations:
        aegis.io/imported-from: aegis-import-898763188.yaml
        aegis.io/severity: low
        kyverno.io/category: Kasten K10 by Veeam in CEL
spec:
    description: Kubernetes applications are typically deployed into a single, logical namespace.  Kasten K10 policies will discover and protect all resources within the selected namespace(s).  This policy ensures all new namespaces include a label referencing a valid K10 SLA  (Policy Preset) for data protection.This policy can be used in combination with generate  ClusterPolicy to automatically create a K10 policy based on the specified SLA.  The combination ensures that new applications are not inadvertently left unprotected.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.matches("(?i)kubectl.*(create|run|apply).*|kubectl.*(patch|edit|set).*")
          message: Kubernetes applications are typically deployed into a single, logical namespace.  Kasten K10 policies will discover and protect all resources within the selected namespace(s).  This policy ensures all new namespaces include a label referencing a valid K10 SLA  (Policy Preset) for data protection.This policy can be used in combination with generate  ClusterPolicy to automatically create a K10 policy based on the specified SLA.  The combination ensures that new applications are not inadvertently left unprotected.
          action: AUDIT
    defaultAction: ALLOW
