# imported from: policies via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-restrict-sa-automount-sa-token-validate-sa-automountserviceaccounttoken-serviceaccount
    annotations:
        aegis.io/imported-from: aegis-import-4053677017.yaml
        aegis.io/severity: medium
        kyverno.io/category: Security
spec:
    description: 'Kubernetes automatically mounts ServiceAccount credentials in each ServiceAccount. The ServiceAccount may be assigned roles allowing Pods to access API resources. Blocking this ability is an extension of the least privilege best practice and should be followed if Pods do not need to speak to the API server to function. This policy ensures that mounting of these ServiceAccount tokens is blocked.      '
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.matches("(?i)kubectl.*")
          message: ServiceAccounts must set automountServiceAccountToken to false.
          action: REQUIRE_APPROVAL
    defaultAction: ALLOW
