# imported from: policies via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-disallow-deprecated-apis-check-deprecated-apis-authorization-openshift-io-v1-role
    annotations:
        aegis.io/imported-from: aegis-import-1968449821.yaml
        aegis.io/severity: medium
        kyverno.io/category: OpenShift
spec:
    description: 'OpenShift APIs are sometimes deprecated and removed after a few releases. As a best practice, older API versions should be replaced with newer versions. This policy validates for APIs that are deprecated or scheduled for removal. Note that checking for some of these resources may require modifying the Kyverno ConfigMap to remove filters.      '
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.matches("(?i)kubectl.*")
          message: '{{ request.object.apiVersion }}/{{ request.object.kind }} is deprecated.'
          action: DENY
    defaultAction: ALLOW
