# imported from: policies via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-restrict-secrets-by-name-safe-secrets-from-envfrom-pod
    annotations:
        aegis.io/imported-from: aegis-import-3137135235.yaml
        aegis.io/severity: low
        kyverno.io/category: Other
spec:
    description: Secrets often contain sensitive information and their access should be carefully controlled. Although Kubernetes RBAC can be effective at restricting them in several ways, it lacks the ability to use wildcards in resource names. This policy ensures that only Secrets beginning with the name `safe-` can be consumed by Pods. In order to work effectively, this policy needs to be paired with a separate policy or rule to require `automountServiceAccountToken=false` since this would otherwise result in a Secret being mounted.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.matches("(?i)kubectl.*(delete\\s+pod|exec|run)")
          message: Only Secrets beginning with `safe-` may be consumed in envFrom statements.
          action: DENY
    defaultAction: ALLOW
