# imported from: policies via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-enforce-ambient-mode-namespace-check-amblient-mode-enabled-namespace
    annotations:
        aegis.io/imported-from: aegis-import-984287049.yaml
        aegis.io/severity: medium
        kyverno.io/category: Istio
spec:
    description: In order for Istio to include namespaces in ambient mode, the label `istio.io/dataplane-mode` must be set to `ambient`. This policy ensures that all new Namespaces set `istio.io/dataplane-mode` to `ambient`.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.matches("(?i)kubectl.*(delete\s+namespace|create\s+namespace)")
          message: All new Namespaces must have Istio ambient mode enabled.
          action: REQUIRE_APPROVAL
    defaultAction: ALLOW
