# imported from: policies via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-block-images-with-volumes-block-images-with-vols-pod
    annotations:
        aegis.io/imported-from: aegis-import-4205862899.yaml
        aegis.io/severity: medium
        kyverno.io/category: Other
spec:
    description: OCI images may optionally be built with VOLUME statements which, if run in read-only mode, would still result in write access to the specified location. This may be unexpected and undesirable. This policy checks the contents of every container image and inspects them for such VOLUME statements, then blocks if found.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.matches("(?i)kubectl.*(delete\s+pod|exec|run)")
          message: Images containing built-in volumes are prohibited.
          action: REQUIRE_APPROVAL
    defaultAction: ALLOW
