# imported from: policies via nixis policy import
apiVersion: nixis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-kasten-generate-policy-by-preset-label-kasten-generate-policy-by-preset-label
    annotations:
        nixis.io/imported-from: nixis-import-3807547480.yaml
        nixis.io/severity: low
        kyverno.io/category: Veeam Kasten
spec:
    description: Generates a Kasten policy for a new namespace that includes a valid "dataprotection" label, if the policy does not already exist. Use with "kasten-validate-ns-by-preset-label" policy to require "dataprotection" labeling on new namespaces.
    matchConstraints:
        tools: []
    validations:
        - expression: 'false'
          message: 'Generate rule — Nixis does not generate resources — manual review required'
          action: AUDIT
    defaultAction: ALLOW
