# IMPORT_TODO: generate rule — Aegis does not generate resources
# imported from: policies via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-generate-flux-multi-tenant-resources-generate-flux-sa
    annotations:
        aegis.io/imported-from: aegis-import-2357560384.yaml
        aegis.io/severity: low
        kyverno.io/category: Flux
spec:
    description: As part of the tenant provisioning process, Flux needs to generate RBAC resources. This policy will create a ServiceAccount and RoleBinding when a new or existing Namespace is labeled with `toolkit.fluxcd.io/tenant`. Use of this rule may require an additional binding for the Kyverno ServiceAccount so it has permissions to properly create the RoleBinding.
    matchConstraints:
        tools: []
    validations:
        - expression: "false"
          message: 'IMPORT_TODO: generate rule — Aegis does not generate resources — manual review required'
          action: AUDIT
    defaultAction: ALLOW
