# imported from: policies via nixis policy import
apiVersion: nixis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-deny-exec-by-pod-and-container-deny-nginx-exec-in-myapp-maintenance-pod-exec
    annotations:
        nixis.io/imported-from: nixis-import-1409289201.yaml
        nixis.io/severity: low
        kyverno.io/category: Sample
spec:
    description: The `exec` command may be used to gain shell access, or run other commands, in a Pod's container. While this can be useful for troubleshooting purposes, it could represent an attack vector and is discouraged. This policy blocks Pod exec commands to containers named `nginx` in Pods starting with name `myapp-maintenance`.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: 'tool == "Bash" && request.args.command.matches(".*kubectl\\s+exec.*\\bmyapp-maintenance\\b.*") && request.args.command.matches(".*-c\\s+nginx.*")'
          message: Nginx containers inside myapp-maintenance Pods may not be exec'd into.
          action: DENY
    defaultAction: ALLOW
