# imported from: policies via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-require-replicas-allow-disruption-replicas-check-deployment
    annotations:
        aegis.io/imported-from: aegis-import-629933210.yaml
        aegis.io/severity: low
        kyverno.io/category: Other
spec:
    description: Existing PodDisruptionBudgets can apply to all future matching Pod controllers. If the minAvailable field is defined for such matching PDBs and the replica count of a new Deployment or StatefulSet is lower than that, then availability could be negatively impacted. This policy specifies that Deployment/StatefulSet replicas exceed the minAvailable value of all matching PodDisruptionBudgets which specify minAvailable as a number and not percentage.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.matches("(?i)kubectl.*(create|run|apply).*|kubectl.*(patch|edit|set).*")
          message: Replica count ({{ request.object.spec.replicas }}) cannot be less than or equal to the minAvailable of any matching PodDisruptionBudget. There are {{ length(matchingpdbs) }} PodDisruptionBudgets which match this labelSelector, not all of which may define a minAvailable value as a number.
          action: AUDIT
    defaultAction: ALLOW
