# IMPORT_TODO: mutate rule — Aegis does not mutate requests
# imported from: policies via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-replace-image-registry-replace-image-registry-pod-containers
    annotations:
        aegis.io/imported-from: aegis-import-4177475608.yaml
        aegis.io/severity: medium
        kyverno.io/category: Sample
spec:
    description: 'Rather than blocking Pods which come from outside registries, it is also possible to mutate them so the pulls are directed to approved registries. In some cases, those registries may function as pull-through proxies and can fetch the image if not cached. This policy mutates all images either in the form ''image:tag'' or ''registry.corp.com/image:tag'' to be `myregistry.corp.com/`. Any path in the image name will be preserved. Note that this mutates Pods directly and not their controllers. It can be changed if desired but if so may need to not match on Pods.      '
    matchConstraints:
        tools: []
    validations:
        - expression: "false"
          message: 'IMPORT_TODO: mutate rule — Aegis does not mutate requests — manual review required'
          action: AUDIT
    defaultAction: ALLOW
