# imported from: policies via aegis policy import
apiVersion: aegis.io/v1
kind: PolicyTemplate
metadata:
    name: kyverno-advanced-restrict-image-registries-validate-corp-registries-pod
    annotations:
        aegis.io/imported-from: aegis-import-2478086530.yaml
        aegis.io/severity: medium
        kyverno.io/category: Other
spec:
    description: In instances where a ClusterPolicy defines all the approved image registries is insufficient, more granular control may be needed to set permitted registries, especially in multi-tenant use cases where some registries may be based on the Namespace. This policy shows an advanced version of the Restrict Image Registries policy which gets a global approved registry from a ConfigMap and, based upon an annotation at the Namespace level, gets the registry approved for that Namespace.
    matchConstraints:
        tools:
            - Bash
    validations:
        - expression: tool == "Bash" && request.args.command.matches("(?i)kubectl.*(delete\\s+pod|exec|run)")
          message: This Pod names an image that is not from an approved registry.
          action: REQUIRE_APPROVAL
    defaultAction: ALLOW
